# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import ukg_python_sdk
from ukg_python_sdk.model.code_tables_get_info429_response import CodeTablesGetInfo429Response
from ukg_python_sdk import configuration


class TestCodeTablesGetInfo429Response(unittest.TestCase):
    """CodeTablesGetInfo429Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
