# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import ukg_python_sdk
from ukg_python_sdk.model.new_hires_create_single_new_hire_request_contact_information_name_prefix import NewHiresCreateSingleNewHireRequestContactInformationNamePrefix
from ukg_python_sdk import configuration


class TestNewHiresCreateSingleNewHireRequestContactInformationNamePrefix(unittest.TestCase):
    """NewHiresCreateSingleNewHireRequestContactInformationNamePrefix unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
