# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import ukg_python_sdk
from ukg_python_sdk.model.new_hires_create_single_new_hire409_response import NewHiresCreateSingleNewHire409Response
from ukg_python_sdk import configuration


class TestNewHiresCreateSingleNewHire409Response(unittest.TestCase):
    """NewHiresCreateSingleNewHire409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
