# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import ukg_python_sdk
from ukg_python_sdk.model.employee_security_user_details_get_details404_response import EmployeeSecurityUserDetailsGetDetails404Response
from ukg_python_sdk import configuration


class TestEmployeeSecurityUserDetailsGetDetails404Response(unittest.TestCase):
    """EmployeeSecurityUserDetailsGetDetails404Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
