# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import ukg_python_sdk
from ukg_python_sdk.model.military_branches_get_all_configurations_response import MilitaryBranchesGetAllConfigurationsResponse
from ukg_python_sdk import configuration


class TestMilitaryBranchesGetAllConfigurationsResponse(unittest.TestCase):
    """MilitaryBranchesGetAllConfigurationsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
