# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import ukg_python_sdk
from ukg_python_sdk.model.employee_employment_details_get_details500_response import EmployeeEmploymentDetailsGetDetails500Response
from ukg_python_sdk import configuration


class TestEmployeeEmploymentDetailsGetDetails500Response(unittest.TestCase):
    """EmployeeEmploymentDetailsGetDetails500Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
