# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import ukg_python_sdk
from ukg_python_sdk.model.employee_pay_statement_earnings_model import EmployeePayStatementEarningsModel
from ukg_python_sdk import configuration


class TestEmployeePayStatementEarningsModel(unittest.TestCase):
    """EmployeePayStatementEarningsModel unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
