# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from ukg_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from ukg_python_sdk.api_response import AsyncGeneratorResponse
from ukg_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ukg_python_sdk import schemas  # noqa: F401

from ukg_python_sdk.model.emp_deductions_list404_response import EmpDeductionsList404Response as EmpDeductionsList404ResponseSchema
from ukg_python_sdk.model.emp_deductions_list500_response import EmpDeductionsList500Response as EmpDeductionsList500ResponseSchema
from ukg_python_sdk.model.emp_deductions_list_response import EmpDeductionsListResponse as EmpDeductionsListResponseSchema
from ukg_python_sdk.model.emp_deductions_list200_response import EmpDeductionsList200Response as EmpDeductionsList200ResponseSchema

from ukg_python_sdk.type.emp_deductions_list200_response import EmpDeductionsList200Response
from ukg_python_sdk.type.emp_deductions_list404_response import EmpDeductionsList404Response
from ukg_python_sdk.type.emp_deductions_list500_response import EmpDeductionsList500Response
from ukg_python_sdk.type.emp_deductions_list_response import EmpDeductionsListResponse

from ...api_client import Dictionary
from ukg_python_sdk.pydantic.emp_deductions_list_response import EmpDeductionsListResponse as EmpDeductionsListResponsePydantic
from ukg_python_sdk.pydantic.emp_deductions_list500_response import EmpDeductionsList500Response as EmpDeductionsList500ResponsePydantic
from ukg_python_sdk.pydantic.emp_deductions_list200_response import EmpDeductionsList200Response as EmpDeductionsList200ResponsePydantic
from ukg_python_sdk.pydantic.emp_deductions_list404_response import EmpDeductionsList404Response as EmpDeductionsList404ResponsePydantic

from . import path

# Query params


class EmployeeIdSchema(
    schemas.StrSchema
):


    class MetaOapg:
        regex=[{
            'pattern': r'^[a-zA-Z0-9]*$',
        }]
CompanyIdSchema = schemas.StrSchema
DedCodeSchema = schemas.StrSchema
BenStatusSchema = schemas.StrSchema
BenefitOptionSchema = schemas.StrSchema
EndDateTimeSchema = schemas.DateTimeSchema


class PageSchema(
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        inclusive_maximum = 2147483647
        inclusive_minimum = 1


class PerPageSchema(
    schemas.Int32Schema
):


    class MetaOapg:
        format = 'int32'
        inclusive_maximum = 2147483647
        inclusive_minimum = 1
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'dedCode': typing.Union[DedCodeSchema, str, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'employeeId': typing.Union[EmployeeIdSchema, str, ],
        'companyId': typing.Union[CompanyIdSchema, str, ],
        'benStatus': typing.Union[BenStatusSchema, str, ],
        'benefitOption': typing.Union[BenefitOptionSchema, str, ],
        'endDateTime': typing.Union[EndDateTimeSchema, str, datetime, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
        'per_Page': typing.Union[PerPageSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_employee_id = api_client.QueryParameter(
    name="employeeId",
    style=api_client.ParameterStyle.FORM,
    schema=EmployeeIdSchema,
    explode=True,
)
request_query_company_id = api_client.QueryParameter(
    name="companyId",
    style=api_client.ParameterStyle.FORM,
    schema=CompanyIdSchema,
    explode=True,
)
request_query_ded_code = api_client.QueryParameter(
    name="dedCode",
    style=api_client.ParameterStyle.FORM,
    schema=DedCodeSchema,
    required=True,
    explode=True,
)
request_query_ben_status = api_client.QueryParameter(
    name="benStatus",
    style=api_client.ParameterStyle.FORM,
    schema=BenStatusSchema,
    explode=True,
)
request_query_benefit_option = api_client.QueryParameter(
    name="benefitOption",
    style=api_client.ParameterStyle.FORM,
    schema=BenefitOptionSchema,
    explode=True,
)
request_query_end_date_time = api_client.QueryParameter(
    name="endDateTime",
    style=api_client.ParameterStyle.FORM,
    schema=EndDateTimeSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
request_query_per_page = api_client.QueryParameter(
    name="per_Page",
    style=api_client.ParameterStyle.FORM,
    schema=PerPageSchema,
    explode=True,
)
_auth = [
    'OauthSecurity',
]
SchemaFor200ResponseBodyApplicationJson = EmpDeductionsListResponseSchema
SchemaFor200ResponseBodyTextJson = EmpDeductionsList200ResponseSchema
SchemaFor200ResponseBodyApplicationProblemjson = EmpDeductionsList200ResponseSchema
SchemaFor200ResponseBodyApplicationXml = EmpDeductionsList200ResponseSchema
SchemaFor200ResponseBodyTextXml = EmpDeductionsList200ResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: EmpDeductionsListResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: EmpDeductionsListResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'text/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyTextJson),
        'application/problem+json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationProblemjson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationXml),
        'text/xml': api_client.MediaType(
            schema=SchemaFor200ResponseBodyTextXml),
    },
)
SchemaFor404ResponseBodyApplicationJson = EmpDeductionsList404ResponseSchema
SchemaFor404ResponseBodyTextJson = EmpDeductionsList404ResponseSchema
SchemaFor404ResponseBodyApplicationProblemjson = EmpDeductionsList404ResponseSchema
SchemaFor404ResponseBodyApplicationXml = EmpDeductionsList404ResponseSchema
SchemaFor404ResponseBodyTextXml = EmpDeductionsList404ResponseSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: EmpDeductionsList404Response


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: EmpDeductionsList404Response


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
        'text/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyTextJson),
        'application/problem+json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationProblemjson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationXml),
        'text/xml': api_client.MediaType(
            schema=SchemaFor404ResponseBodyTextXml),
    },
)
SchemaFor500ResponseBodyApplicationJson = EmpDeductionsList500ResponseSchema
SchemaFor500ResponseBodyTextJson = EmpDeductionsList500ResponseSchema
SchemaFor500ResponseBodyApplicationProblemjson = EmpDeductionsList500ResponseSchema
SchemaFor500ResponseBodyApplicationXml = EmpDeductionsList500ResponseSchema
SchemaFor500ResponseBodyTextXml = EmpDeductionsList500ResponseSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: EmpDeductionsList500Response


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: EmpDeductionsList500Response


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
        'text/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyTextJson),
        'application/problem+json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationProblemjson),
        'application/xml': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationXml),
        'text/xml': api_client.MediaType(
            schema=SchemaFor500ResponseBodyTextXml),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '404': _response_for_404,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
    'text/json',
    'application/problem+json',
    'application/xml',
    'text/xml',
)


class BaseApi(api_client.Api):

    def _list_mapped_args(
        self,
        ded_code: str,
        employee_id: typing.Optional[str] = None,
        company_id: typing.Optional[str] = None,
        ben_status: typing.Optional[str] = None,
        benefit_option: typing.Optional[str] = None,
        end_date_time: typing.Optional[datetime] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if employee_id is not None:
            _query_params["employeeId"] = employee_id
        if company_id is not None:
            _query_params["companyId"] = company_id
        if ded_code is not None:
            _query_params["dedCode"] = ded_code
        if ben_status is not None:
            _query_params["benStatus"] = ben_status
        if benefit_option is not None:
            _query_params["benefitOption"] = benefit_option
        if end_date_time is not None:
            _query_params["endDateTime"] = end_date_time
        if page is not None:
            _query_params["page"] = page
        if per_page is not None:
            _query_params["per_Page"] = per_page
        args.query = _query_params
        return args

    async def _alist_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get employee deductions
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_employee_id,
            request_query_company_id,
            request_query_ded_code,
            request_query_ben_status,
            request_query_benefit_option,
            request_query_end_date_time,
            request_query_page,
            request_query_per_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/personnel/v1/emp-deductions',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get employee deductions
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_employee_id,
            request_query_company_id,
            request_query_ded_code,
            request_query_ben_status,
            request_query_benefit_option,
            request_query_end_date_time,
            request_query_page,
            request_query_per_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/personnel/v1/emp-deductions',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist(
        self,
        ded_code: str,
        employee_id: typing.Optional[str] = None,
        company_id: typing.Optional[str] = None,
        ben_status: typing.Optional[str] = None,
        benefit_option: typing.Optional[str] = None,
        end_date_time: typing.Optional[datetime] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_mapped_args(
            ded_code=ded_code,
            employee_id=employee_id,
            company_id=company_id,
            ben_status=ben_status,
            benefit_option=benefit_option,
            end_date_time=end_date_time,
            page=page,
            per_page=per_page,
        )
        return await self._alist_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def list(
        self,
        ded_code: str,
        employee_id: typing.Optional[str] = None,
        company_id: typing.Optional[str] = None,
        ben_status: typing.Optional[str] = None,
        benefit_option: typing.Optional[str] = None,
        end_date_time: typing.Optional[datetime] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_mapped_args(
            ded_code=ded_code,
            employee_id=employee_id,
            company_id=company_id,
            ben_status=ben_status,
            benefit_option=benefit_option,
            end_date_time=end_date_time,
            page=page,
            per_page=per_page,
        )
        return self._list_oapg(
            query_params=args.query,
        )

class List(BaseApi):

    async def alist(
        self,
        ded_code: str,
        employee_id: typing.Optional[str] = None,
        company_id: typing.Optional[str] = None,
        ben_status: typing.Optional[str] = None,
        benefit_option: typing.Optional[str] = None,
        end_date_time: typing.Optional[datetime] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> EmpDeductionsListResponsePydantic:
        raw_response = await self.raw.alist(
            ded_code=ded_code,
            employee_id=employee_id,
            company_id=company_id,
            ben_status=ben_status,
            benefit_option=benefit_option,
            end_date_time=end_date_time,
            page=page,
            per_page=per_page,
            **kwargs,
        )
        if validate:
            return RootModel[EmpDeductionsListResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(EmpDeductionsListResponsePydantic, raw_response.body)
    
    
    def list(
        self,
        ded_code: str,
        employee_id: typing.Optional[str] = None,
        company_id: typing.Optional[str] = None,
        ben_status: typing.Optional[str] = None,
        benefit_option: typing.Optional[str] = None,
        end_date_time: typing.Optional[datetime] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        validate: bool = False,
    ) -> EmpDeductionsListResponsePydantic:
        raw_response = self.raw.list(
            ded_code=ded_code,
            employee_id=employee_id,
            company_id=company_id,
            ben_status=ben_status,
            benefit_option=benefit_option,
            end_date_time=end_date_time,
            page=page,
            per_page=per_page,
        )
        if validate:
            return RootModel[EmpDeductionsListResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(EmpDeductionsListResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        ded_code: str,
        employee_id: typing.Optional[str] = None,
        company_id: typing.Optional[str] = None,
        ben_status: typing.Optional[str] = None,
        benefit_option: typing.Optional[str] = None,
        end_date_time: typing.Optional[datetime] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_mapped_args(
            ded_code=ded_code,
            employee_id=employee_id,
            company_id=company_id,
            ben_status=ben_status,
            benefit_option=benefit_option,
            end_date_time=end_date_time,
            page=page,
            per_page=per_page,
        )
        return await self._alist_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        ded_code: str,
        employee_id: typing.Optional[str] = None,
        company_id: typing.Optional[str] = None,
        ben_status: typing.Optional[str] = None,
        benefit_option: typing.Optional[str] = None,
        end_date_time: typing.Optional[datetime] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_mapped_args(
            ded_code=ded_code,
            employee_id=employee_id,
            company_id=company_id,
            ben_status=ben_status,
            benefit_option=benefit_option,
            end_date_time=end_date_time,
            page=page,
            per_page=per_page,
        )
        return self._list_oapg(
            query_params=args.query,
        )

