# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ApplicationHireDetailsCompany(BaseModel):
    # The id of the legal entity associated with the specified application. If not specified, it will be defaulted to the legal entity associated with the opportunity for the application.
    id: typing.Optional[str] = Field(None, alias='id')

    # The legal entity name
    name: typing.Optional[str] = Field(None, alias='name')

    # The legal entity code
    code: typing.Optional[str] = Field(None, alias='code')

    # The legal entity’s Doing Business As name
    doing_business_as: typing.Optional[str] = Field(None, alias='doing_business_as')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
