# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AuditDetails(BaseModel):
    aud_date_time: typing.Optional[datetime] = Field(None, alias='audDateTime')

    aud_key1_label: typing.Optional[str] = Field(None, alias='audKey1Label')

    aud_key2_label: typing.Optional[str] = Field(None, alias='audKey2Label')

    aud_key3_label: typing.Optional[str] = Field(None, alias='audKey3Label')

    aud_key1_value: typing.Optional[str] = Field(None, alias='audKey1Value')

    aud_key2_value: typing.Optional[str] = Field(None, alias='audKey2Value')

    aud_key3_value: typing.Optional[str] = Field(None, alias='audKey3Value')

    aud_table_name: typing.Optional[str] = Field(None, alias='audTableName')

    aud_field_name: typing.Optional[str] = Field(None, alias='audFieldName')

    aud_old_value: typing.Optional[str] = Field(None, alias='audOldValue')

    aud_new_value: typing.Optional[str] = Field(None, alias='audNewValue')

    aud_action: typing.Optional[str] = Field(None, alias='audAction')

    aud_system_i_d: typing.Optional[str] = Field(None, alias='audSystemID')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
