# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CompanyPayStatementFilter(BaseModel):
    start_date: datetime = Field(alias='startDate')

    end_date: datetime = Field(alias='endDate')

    company_id: typing.Optional[str] = Field(None, alias='companyId')

    pay_group: typing.Optional[str] = Field(None, alias='payGroup')

    page: typing.Optional[int] = Field(None, alias='page')

    per__page: typing.Optional[int] = Field(None, alias='per_Page')

    pages_count: typing.Optional[int] = Field(None, alias='pagesCount')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
