# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from ukg_python_sdk.pydantic.creator_background_check_integration import CreatorBackgroundCheckIntegration
from ukg_python_sdk.pydantic.creator_contact_info import CreatorContactInfo
from ukg_python_sdk.pydantic.creator_name import CreatorName
from ukg_python_sdk.pydantic.creator_preferred_locale import CreatorPreferredLocale
from ukg_python_sdk.pydantic.creator_roles import CreatorRoles
from ukg_python_sdk.pydantic.hyperlinks import Hyperlinks
from ukg_python_sdk.pydantic.links import Links

class Creator(BaseModel):
    # The id of the recruiter who created the background check order.
    id: typing.Optional[str] = Field(None, alias='id')

    # The recruiter id in the core HR system.
    person_id: typing.Optional[str] = Field(None, alias='person_id')

    # The date of this user creation date.
    created_at: typing.Optional[str] = Field(None, alias='created_at')

    # The alternative user id that can be used in third-party vendors’ integrations. Returned only for users with the “recruiter”, “hiring-manager”, or “recruiting-administrator” role.
    integration_user_id: typing.Optional[str] = Field(None, alias='integration_user_id')

    # A flag indicating whether the recruiter is an internal employee. 
    is_internal: typing.Optional[bool] = Field(None, alias='is_internal')

    # A flag indicating whether the recruiter is an active employee. Can only be specified when is_internal is true.
    is_active: typing.Optional[bool] = Field(None, alias='is_active')

    preferred_locale: typing.Optional[CreatorPreferredLocale] = Field(None, alias='preferred_locale')

    name: typing.Optional[CreatorName] = Field(None, alias='name')

    contact_info: typing.Optional[CreatorContactInfo] = Field(None, alias='contact_info')

    roles: typing.Optional[CreatorRoles] = Field(None, alias='roles')

    hyperlinks: typing.Optional[typing.List[Hyperlinks]] = Field(None, alias='hyperlinks')

    updated_at: typing.Optional[str] = Field(None, alias='updated_at')

    links: typing.Optional[typing.List[Links]] = Field(None, alias='links')

    background_check_integration: typing.Optional[CreatorBackgroundCheckIntegration] = Field(None, alias='background_check_integration')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
