# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class EmployeeMultiPhoneNumbers(BaseModel):
    employee_id: typing.Optional[str] = Field(None, alias='employeeId')

    audit_key: typing.Optional[str] = Field(None, alias='auditKey')

    first_name: typing.Optional[str] = Field(None, alias='firstName')

    former_name: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='formerName')

    last_name: typing.Optional[str] = Field(None, alias='lastName')

    middle_name: typing.Optional[str] = Field(None, alias='middleName')

    phone_number: typing.Optional[str] = Field(None, alias='phoneNumber')

    phone_country_code: typing.Optional[str] = Field(None, alias='phoneCountryCode')

    phone_country_prefix: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='phoneCountryPrefix')

    phone_type_code: typing.Optional[str] = Field(None, alias='phoneTypeCode')

    phone_extension: typing.Optional[str] = Field(None, alias='phoneExtension')

    phone_is_private: typing.Optional[bool] = Field(None, alias='phoneIsPrivate')

    system_id: typing.Optional[str] = Field(None, alias='systemId')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
