# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class NewHiresGetByIdResponseOrganizationLevelsItem(BaseModel):
    # Description of a organization that the new hire is associated with.
    description: typing.Optional[str] = Field(None, alias='description')

    # Identifier of the organization level
    id: typing.Optional[str] = Field(None, alias='id')

    # Level of the organization level
    level: typing.Optional[Literal["Level 1 = 1", "Level 2 = 2", "Level 3 = 3", "Level 4 = 4"]] = Field(None, alias='level')

    # Unique code of a organization that the new hire is associated with
    code: typing.Optional[str] = Field(None, alias='code')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
