# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from ukg_python_sdk.pydantic.new_hires_create_single_new_hire201_response_provisioning_provisioning_items import NewHiresCreateSingleNewHire201ResponseProvisioningProvisioningItems
from ukg_python_sdk.pydantic.new_hires_create_single_new_hire201_response_provisioning_summary_email_recipients import NewHiresCreateSingleNewHire201ResponseProvisioningSummaryEmailRecipients

class NewHiresCreateSingleNewHire201ResponseProvisioning(BaseModel):
    provisioning_items: typing.Optional[NewHiresCreateSingleNewHire201ResponseProvisioningProvisioningItems] = Field(None, alias='provisioningItems')

    summary_email_recipients: typing.Optional[NewHiresCreateSingleNewHire201ResponseProvisioningSummaryEmailRecipients] = Field(None, alias='summaryEmailRecipients')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
