# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from ukg_python_sdk.pydantic.new_hires_get_by_id200_response_provisioning_provisioning_items_item_selected_option import NewHiresGetById200ResponseProvisioningProvisioningItemsItemSelectedOption

class NewHiresGetById200ResponseProvisioningProvisioningItemsItem(BaseModel):
    # Id of the provisioning item
    id: typing.Optional[str] = Field(None, alias='id')

    # Category of the provisioning item
    name: typing.Optional[str] = Field(None, alias='name')

    # Recipient of the provisioning item
    recipient: typing.Optional[str] = Field(None, alias='recipient')

    selected_option: typing.Optional[NewHiresGetById200ResponseProvisioningProvisioningItemsItemSelectedOption] = Field(None, alias='selectedOption')

    # Comment on the provisioning item
    comments: typing.Optional[str] = Field(None, alias='comments')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
