# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from ukg_python_sdk.pydantic.skill_proficiency_level import SkillProficiencyLevel
from ukg_python_sdk.pydantic.skill_skill import SkillSkill

class Skill(BaseModel):
    # The id of the candidate’s skill/proficiency level record 
    id: typing.Optional[str] = Field(None, alias='id')

    skill: typing.Optional[SkillSkill] = Field(None, alias='skill')

    proficiency_level: typing.Optional[SkillProficiencyLevel] = Field(None, alias='proficiency_level')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
