# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredApplicationOpportunity(TypedDict):
    pass

class OptionalApplicationOpportunity(TypedDict, total=False):
    # The id of the opportunity that the candidate has applied for.
    id: str

class ApplicationOpportunity(RequiredApplicationOpportunity, OptionalApplicationOpportunity):
    pass
