# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ukg_python_sdk.type.employee_pay_statement_identifier_model import EmployeePayStatementIdentifierModel

class RequiredCompanyPayStatementModel(TypedDict):
    pass

class OptionalCompanyPayStatementModel(TypedDict, total=False):
    employeeidentifier: EmployeePayStatementIdentifierModel

    payidentifier: str

    paydate: datetime

    document: str

    totalearnings: typing.Union[int, float]

    totaldeductions: typing.Union[int, float]

    totaltaxes: typing.Union[int, float]

class CompanyPayStatementModel(RequiredCompanyPayStatementModel, OptionalCompanyPayStatementModel):
    pass
