# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ukg_python_sdk.type.contact_info_address_country import ContactInfoAddressCountry

class RequiredContactInfoAddress(TypedDict):
    pass

class OptionalContactInfoAddress(TypedDict, total=False):
    # The candidate’s address line 1. Maximum of 255 characters.
    line1: str

    # The candidate’s address line 2. Maximum of 255 characters.
    line2: str

    # The candidate’s address city. Maximum of 255 characters.
    city: str

    state: str

    # The candidate’s postal code. Must be between 3 and 50 characters.
    postal_Code: str

    country: ContactInfoAddressCountry

class ContactInfoAddress(RequiredContactInfoAddress, OptionalContactInfoAddress):
    pass
