# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDependentDeductions(TypedDict):
    pass

class OptionalDependentDeductions(TypedDict, total=False):
    benefitAmount: typing.Union[int, float]

    benefitStartDate: datetime

    benefitStatus: str

    benefitStatusDate: datetime

    benefitStopDate: datetime

    certificateNo: str

    companyID: str

    contactID: str

    currentCOID: str

    dateTimeChanged: datetime

    dateTimeCreated: datetime

    declinedByCarrierDate: datetime

    deductionCode: str

    deductionNotes: str

    deductionType: str

    declinedByCarrier: str

    declinedByCarrierReason: str

    depBPlanTVID: int

    systemID: str

    employeeId: str

    eoiDate: datetime

    needEOI: bool

    primaryCarePhysician: str

    primaryCarePhysicianId: str

    isBenefitWaived: bool

class DependentDeductions(RequiredDependentDeductions, OptionalDependentDeductions):
    pass
