# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmpCompensationDetails(TypedDict):
    pass

class OptionalEmpCompensationDetails(TypedDict, total=False):
    employeeID: str

    companyID: str

    annualSalary: typing.Union[int, float]

    hourlyPayRate: typing.Union[int, float]

    weeklyPayRate: typing.Union[int, float]

    payPeriodPayRate: typing.Union[int, float]

    currencyCode: str

    otherRate1: typing.Union[int, float]

    otherRate2: typing.Union[int, float]

    otherRate3: typing.Union[int, float]

    otherRate4: typing.Union[int, float]

    payGroupDescription: str

    piecePayRate: typing.Union[int, float]

    primaryJobCode: str

    jobSalaryGrade: str

    jobChangeReasonCode: str

    jobGroupCode: str

    jobTitle: str

    dateInJob: datetime

    dateLastPaid: datetime

    dateLastWorked: datetime

    dateOfLastSalaryReview: datetime

    dateOfNextSalayrReview: datetime

    isAutoAllocated: bool

    isAutoPaid: bool

    isSeasonalWorker: bool

    isHighlyCompensated: bool

    isMultipleJob: bool

    payGroupCode: str

    payPeriod: str

    payScaleCode: str

    salaryOrHourlyCode: str

    fullTimeOrPartTimeCode: str

    scheduledFullTimeEquivalency: typing.Union[int, float]

    scheduledPeriodWorkHours: typing.Union[int, float]

    scheduledAnnualWorkHours: typing.Union[int, float]

    weeklyHours: typing.Union[int, float]

    primaryShiftCode: str

    primaryShiftGroupCode: str

    avgPayRateCurPer: typing.Union[int, float]

    bonusTotalHrs: typing.Union[int, float]

    bonusTotalOtHrs: typing.Union[int, float]

    datePaidThru: datetime

    emplStatus: str

    totalAnnSalary: typing.Union[int, float]

    distributionCenterCode: str

    numberOfPayments: int

    performanceReviewRating: str

    performanceReviewType: str

class EmpCompensationDetails(RequiredEmpCompensationDetails, OptionalEmpCompensationDetails):
    pass
