# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeeSupervisorDetails(TypedDict):
    pass

class OptionalEmployeeSupervisorDetails(TypedDict, total=False):
    employeeID: str

    companyID: str

    employeeNumber: str

    supervisorEmployeeID: str

    supervisorFirstName: str

    supervisorLastName: str

    supervisorEmployeeNumber: str

    supervisorCompanyID: str

    supervisorCompanyCode: str

    supervisorStatusCode: str

    supervisorJobCode: str

    supervisorPositionCode: str

    supervisorEmail: str

    supervisorWorkPhone: str

    supervisorPersonId: str

class EmployeeSupervisorDetails(RequiredEmployeeSupervisorDetails, OptionalEmployeeSupervisorDetails):
    pass
