# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeeEmploymentDetails(TypedDict):
    pass

class OptionalEmployeeEmploymentDetails(TypedDict, total=False):
    companyID: str

    employeeID: str

    primaryJobCode: str

    jobTitle: str

    fullTimeOrPartTimeCode: str

    primaryWorkLocationCode: str

    primaryProjectCode: str

    deductionGroupCode: str

    earningGroupCode: str

    employeeTypeCode: str

    employeeStatusCode: str

    employeeNumber: str

    supervisorId: str

    originalHireDate: str

    lastHireDate: str

    dateOfTermination: str

    dateOfRetirement: str

    dateTimeCreated: str

    dateTimeChanged: str

    dateLastPayDatePaid: str

    payGroup: str

    isHomeCompany: str

    page: int

    per_Page: int

class EmployeeEmploymentDetails(RequiredEmployeeEmploymentDetails, OptionalEmployeeEmploymentDetails):
    pass
