# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ukg_python_sdk.type.employee_pay_statement_accruals_model import EmployeePayStatementAccrualsModel
from ukg_python_sdk.type.employee_pay_statement_deductions_model import EmployeePayStatementDeductionsModel
from ukg_python_sdk.type.employee_pay_statement_earnings_model import EmployeePayStatementEarningsModel
from ukg_python_sdk.type.employee_pay_statement_identifier_model import EmployeePayStatementIdentifierModel
from ukg_python_sdk.type.employee_pay_statement_net_pay_model import EmployeePayStatementNetPayModel
from ukg_python_sdk.type.employee_pay_statement_taxes_model import EmployeePayStatementTaxesModel

class RequiredEmployeePayStatementModel(TypedDict):
    pass

class OptionalEmployeePayStatementModel(TypedDict, total=False):
    accruals: typing.List[EmployeePayStatementAccrualsModel]

    addressline1: str

    addressline2: str

    city: str

    companyaddresscity: str

    companyaddresscountry: str

    companyaddresscounty: str

    companyaddressline1: str

    companyaddressline2: str

    companyaddresspostalcode: str

    companyaddressstateorprovince: str

    companyname: str

    companyphone: str

    companyphoneext: str

    country: str

    deductions: typing.List[EmployeePayStatementDeductionsModel]

    deductionscurrent: typing.Union[int, float]

    deductionsytd: typing.Union[int, float]

    document: str

    earnings: typing.List[EmployeePayStatementEarningsModel]

    employeeidentifier: EmployeePayStatementIdentifierModel

    employeenumber: str

    federaladditionalamountWithheld: typing.Union[int, float]

    federalallowancesclaimed: int

    federalfilingstatus: str

    federaltaxablewagescurrent: typing.Union[int, float]

    federaltaxablewagesytd: typing.Union[int, float]

    fullname: str

    grosswagescurrent: typing.Union[int, float]

    grosswagesytd: typing.Union[int, float]

    job: str

    location: str

    netpay: typing.List[EmployeePayStatementNetPayModel]

    netpaycurrent: typing.Union[int, float]

    netpayytd: typing.Union[int, float]

    orglevel1: str

    orglevel2: str

    orglevel3: str

    orglevel4: str

    paydate: datetime

    payperiodfrequency: str

    paygroup: str

    payidentifier: str

    payrate: typing.Union[int, float]

    periodenddate: datetime

    periodstartdate: datetime

    postalcode: str

    residentstateallowancesclaimed: int

    residentstatefilingstatus: str

    ssn: str

    stateorprovince: str

    taxes: typing.List[EmployeePayStatementTaxesModel]

    taxescurrent: typing.Union[int, float]

    taxesytd: typing.Union[int, float]

    workstateallowancesclaimed: int

    workstatefilingstatus: str

class EmployeePayStatementModel(RequiredEmployeePayStatementModel, OptionalEmployeePayStatementModel):
    pass
