# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeePayStatementEarningsModel(TypedDict):
    pass

class OptionalEmployeePayStatementEarningsModel(TypedDict, total=False):
    amount: typing.Union[int, float]

    amountytd: typing.Union[int, float]

    hours: typing.Union[int, float]

    hoursytd: typing.Union[int, float]

    paycode: str

    paydescription: str

    payrate: typing.Union[int, float]

    periodend: datetime

    periodstart: datetime

    piececount: typing.Union[int, float]

    piecepayrate: typing.Union[int, float]

class EmployeePayStatementEarningsModel(RequiredEmployeePayStatementEarningsModel, OptionalEmployeePayStatementEarningsModel):
    pass
