# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobDto(TypedDict):
    pass

class OptionalJobDto(TypedDict, total=False):
    id: int

    locName: str

    locDesc: str

    name: str

class JobDto(RequiredJobDto, OptionalJobDto):
    pass
