# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ukg_python_sdk.type.positions_user_defined_field04 import PositionsUserDefinedField04

class RequiredPositions(TypedDict):
    pass

class OptionalPositions(TypedDict, total=False):
    alternateTitle: str

    companyId: str

    dateTimeChanged: datetime

    dateTimeCreated: datetime

    employeeType: str

    effectiveStartDate: datetime

    effectiveStopDate: datetime

    fundID: str

    glSegment: str

    isApproved: bool

    isEligibleForBenefits: bool

    isProrated: bool

    jobcode: str

    locationCode: str

    notes: str

    organizationLevelCode1: str

    organizationLevelCode2: str

    organizationLevelCode3: str

    organizationLevelCode4: str

    overstaffingAllowed: bool

    payGroupCode: str

    positionCode: str

    projectCode: str

    shiftGroupCode: str

    statusCode: str

    statusAsOfDate: datetime

    userDefinedField01: str

    userDefinedField02: datetime

    userDefinedField03: typing.Union[int, float]

    userDefinedField04: PositionsUserDefinedField04

    integrationRecordId: str

class Positions(RequiredPositions, OptionalPositions):
    pass
