# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ukg_python_sdk.type.postings_item_education_criteria_item_degree import PostingsItemEducationCriteriaItemDegree
from ukg_python_sdk.type.postings_item_education_criteria_item_major import PostingsItemEducationCriteriaItemMajor

class RequiredPostingsItemEducationCriteriaItem(TypedDict):
    pass

class OptionalPostingsItemEducationCriteriaItem(TypedDict, total=False):
    # Indicates if this education is required for the job.
    is_required: bool

    # Indicates if similar educations will be considered for this job.
    allow_related: bool

    degree: PostingsItemEducationCriteriaItemDegree

    major: PostingsItemEducationCriteriaItemMajor

class PostingsItemEducationCriteriaItem(RequiredPostingsItemEducationCriteriaItem, OptionalPostingsItemEducationCriteriaItem):
    pass
