# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ukg_python_sdk.type.translations import Translations

class RequiredPostingsItemSkillCriteriaItemSkillProficiencyLevel(TypedDict):
    pass

class OptionalPostingsItemSkillCriteriaItemSkillProficiencyLevel(TypedDict, total=False):
    # The unique id of a standard proficiency level (GUID).
    id: str

    name: Translations

    # A numerical equivalent of proficiency_level.name:  1. Novice  2. Some Knowledge  3. Intermediate  4. Advanced 5. Expert
    ordinal_value: typing.Union[int, float]

class PostingsItemSkillCriteriaItemSkillProficiencyLevel(RequiredPostingsItemSkillCriteriaItemSkillProficiencyLevel, OptionalPostingsItemSkillCriteriaItemSkillProficiencyLevel):
    pass
