# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTaxGroupsDetails(TypedDict):
    pass

class OptionalTaxGroupsDetails(TypedDict, total=False):
    taxCalcGroupIdCode: str

    taxCalcGroupDescription: str

    depositFrequencyCode: str

    depositFrequencyDescription: str

    taxCalcGroupTypeCode: str

    taxCalcGroupTypeDescription: str

    taxCalcGroupReportId: str

    taxGroupCountryCode: str

    dateFinalWagesPaid: datetime

    dateMonthReset: datetime

    dateQuarterReset: datetime

    dateYearReset: datetime

    taxGroupIsNotSubjectToSocMedTax: bool

    taxGroupIsNotPayingWages: bool

    taxGroupIsInactive: bool

class TaxGroupsDetails(RequiredTaxGroupsDetails, OptionalTaxGroupsDetails):
    pass
