# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.personnel_v1_audit_details.get import GetData
from ukg_python_sdk.apis.tags.audit_details_api_raw import AuditDetailsApiRaw


class AuditDetailsApi(
    GetData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AuditDetailsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AuditDetailsApiRaw(api_client)
