# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.course_category.post import CreateConfigurationUkgPro
from ukg_python_sdk.paths.course_category.get import GetAllConfigurations
from ukg_python_sdk.paths.course_category_code.put import UpdateConfiguration
from ukg_python_sdk.apis.tags.course_category_api_raw import CourseCategoryApiRaw


class CourseCategoryApi(
    CreateConfigurationUkgPro,
    GetAllConfigurations,
    UpdateConfiguration,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CourseCategoryApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CourseCategoryApiRaw(api_client)
