# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.course_delivery_met.post import CreateConfigurationUkgPro
from ukg_python_sdk.paths.course_delivery_met.get import GetConfigurations
from ukg_python_sdk.paths.course_delivery_met_code.put import UpdateConfiguration
from ukg_python_sdk.apis.tags.course_delivery_met_api_raw import CourseDeliveryMetApiRaw


class CourseDeliveryMetApi(
    CreateConfigurationUkgPro,
    GetConfigurations,
    UpdateConfiguration,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CourseDeliveryMetApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CourseDeliveryMetApiRaw(api_client)
