# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.services_payroll_v1_import_pay_items_earnings.post import AddTimeClockData
from ukg_python_sdk.paths.services_payroll_v1_import_pay_items_earnings_ref_id.delete import DeleteEarning
from ukg_python_sdk.paths.configuration_v1_earnings_calculation_rule_tax_category_use_deduction_offset_country_code_include_in_shift_diffrential_include_in_manual_check.get import GetConfigurationsFilteredByParameter
from ukg_python_sdk.paths.services_payroll_v1_import_pay_items_earnings_ref_id.get import GetStatusDetails
from ukg_python_sdk.paths.configuration_v1_earnings.get import ListEarningsConfigurations
from ukg_python_sdk.paths.configuration_v1_earnings_earning_code.get import SpecificConfigurationGet
from ukg_python_sdk.apis.tags.earnings_api_raw import EarningsApiRaw


class EarningsApi(
    AddTimeClockData,
    DeleteEarning,
    GetConfigurationsFilteredByParameter,
    GetStatusDetails,
    ListEarningsConfigurations,
    SpecificConfigurationGet,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EarningsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EarningsApiRaw(api_client)
