# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.payroll_v1_employees_pay_statements.post import GetByDateRange
from ukg_python_sdk.paths.payroll_v1_employees_pay_statement_pay_identifier.get import GetByPayIdentifier
from ukg_python_sdk.paths.payroll_v1_employees_pay_statement_last.post import GetLastPayStatement
from ukg_python_sdk.apis.tags.employee_pay_statement_api_raw import EmployeePayStatementApiRaw


class EmployeePayStatementApi(
    GetByDateRange,
    GetByPayIdentifier,
    GetLastPayStatement,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeePayStatementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeePayStatementApiRaw(api_client)
