# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.personnel_v1_companies_company_id_employees_employee_id_employment_details.get import GetByCompanyIdAndEmployeeId
from ukg_python_sdk.paths.personnel_v1_employment_details.get import GetDetails
from ukg_python_sdk.paths.personnel_v1_companies_company_id_employment_details.get import ListByCompany
from ukg_python_sdk.apis.tags.employment_details_api_raw import EmploymentDetailsApiRaw


class EmploymentDetailsApi(
    GetByCompanyIdAndEmployeeId,
    GetDetails,
    ListByCompany,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmploymentDetailsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmploymentDetailsApiRaw(api_client)
