# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.personnel_v1_employee_security_user_details.get import GetDetails
from ukg_python_sdk.apis.tags.employee_security_user_details_api_raw import EmployeeSecurityUserDetailsApiRaw


class EmployeeSecurityUserDetailsApi(
    GetDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeeSecurityUserDetailsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeeSecurityUserDetailsApiRaw(api_client)
