# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.configuration_v1_org_levels_level_code.get import Get
from ukg_python_sdk.paths.configuration_v1_org_levels_level_code.put import UpdateOrgLevel
from ukg_python_sdk.paths.configuration_v1_org_levels_level_code.patch import UpdateProperties
from ukg_python_sdk.apis.tags.single_organization_level_api_raw import SingleOrganizationLevelApiRaw


class SingleOrganizationLevelApi(
    Get,
    UpdateOrgLevel,
    UpdateProperties,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SingleOrganizationLevelApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SingleOrganizationLevelApiRaw(api_client)
