# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.skills.post import CreateConfiguration
from ukg_python_sdk.paths.skills.get import GetConfigurations
from ukg_python_sdk.paths.skills_code.put import UpdateConfiguration
from ukg_python_sdk.apis.tags.skills_api_raw import SkillsApiRaw


class SkillsApi(
    CreateConfiguration,
    GetConfigurations,
    UpdateConfiguration,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SkillsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SkillsApiRaw(api_client)
