# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from ukg_python_sdk.paths.configuration_v1_org_levels.post import CreateOrgLevelConfigRaw
from ukg_python_sdk.paths.configuration_v1_org_levels.get import GetAllOrgLevelsRaw


class ViewOrCreateOrganizationLevelsApiRaw(
    CreateOrgLevelConfigRaw,
    GetAllOrgLevelsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
