# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import ukg_python_sdk
from ukg_python_sdk.paths.services_payroll_v1_import_pay_items_earnings import post
from ukg_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestServicesPayrollV1ImportPayItemsEarnings(ApiTestMixin, unittest.TestCase):
    """
    ServicesPayrollV1ImportPayItemsEarnings unit test stubs
        Add UKG Pro time clock data
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201






if __name__ == '__main__':
    unittest.main()
