# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from ukg_python_sdk.paths.configuration_v1_earnings_calculation_rule_tax_category_use_deduction_offset_country_code_include_in_shift_diffrential_include_in_manual_check import Api

from ukg_python_sdk.paths import PathValues

path = PathValues.CONFIGURATION_V1_EARNINGS_CALCULATION_RULE_TAX_CATEGORY_USE_DEDUCTION_OFFSET_COUNTRY_CODE_INCLUDE_IN_SHIFT_DIFFRENTIAL_INCLUDE_IN_MANUAL_CHECK