# coding: utf-8

"""
    User Profile Details

    Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from ukg_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from ukg_python_sdk.api_response import AsyncGeneratorResponse
from ukg_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ukg_python_sdk import schemas  # noqa: F401

from ukg_python_sdk.model.view_or_create_organization_levels_get_all_org_levels200_response import ViewOrCreateOrganizationLevelsGetAllOrgLevels200Response as ViewOrCreateOrganizationLevelsGetAllOrgLevels200ResponseSchema
from ukg_python_sdk.model.view_or_create_organization_levels_get_all_org_levels_response import ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponse as ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponseSchema

from ukg_python_sdk.type.view_or_create_organization_levels_get_all_org_levels_response import ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponse
from ukg_python_sdk.type.view_or_create_organization_levels_get_all_org_levels200_response import ViewOrCreateOrganizationLevelsGetAllOrgLevels200Response

from ...api_client import Dictionary
from ukg_python_sdk.pydantic.view_or_create_organization_levels_get_all_org_levels_response import ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponse as ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponsePydantic
from ukg_python_sdk.pydantic.view_or_create_organization_levels_get_all_org_levels200_response import ViewOrCreateOrganizationLevelsGetAllOrgLevels200Response as ViewOrCreateOrganizationLevelsGetAllOrgLevels200ResponsePydantic

from . import path

# Query params
LevelDescriptionSchema = schemas.StrSchema
CodeSchema = schemas.StrSchema
BudgetGroupSchema = schemas.StrSchema
ReportingCategorySchema = schemas.StrSchema
IsActiveSchema = schemas.BoolSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'levelDescription': typing.Union[LevelDescriptionSchema, str, ],
        'code': typing.Union[CodeSchema, str, ],
        'budgetGroup': typing.Union[BudgetGroupSchema, str, ],
        'reportingCategory': typing.Union[ReportingCategorySchema, str, ],
        'isActive': typing.Union[IsActiveSchema, bool, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_level_description = api_client.QueryParameter(
    name="levelDescription",
    style=api_client.ParameterStyle.FORM,
    schema=LevelDescriptionSchema,
    explode=True,
)
request_query_code = api_client.QueryParameter(
    name="code",
    style=api_client.ParameterStyle.FORM,
    schema=CodeSchema,
    explode=True,
)
request_query_budget_group = api_client.QueryParameter(
    name="budgetGroup",
    style=api_client.ParameterStyle.FORM,
    schema=BudgetGroupSchema,
    explode=True,
)
request_query_reporting_category = api_client.QueryParameter(
    name="reportingCategory",
    style=api_client.ParameterStyle.FORM,
    schema=ReportingCategorySchema,
    explode=True,
)
request_query_is_active = api_client.QueryParameter(
    name="isActive",
    style=api_client.ParameterStyle.FORM,
    schema=IsActiveSchema,
    explode=True,
)
_auth = [
    'OauthSecurity',
]
SchemaFor200ResponseBodyApplicationJson = ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponseSchema
SchemaFor200ResponseBodyApplicationProblemjson = ViewOrCreateOrganizationLevelsGetAllOrgLevels200ResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'application/problem+json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationProblemjson),
    },
)


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
)


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
)


@dataclass
class ApiResponseFor429(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor429Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_429 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor429,
    response_cls_async=ApiResponseFor429Async,
)
_status_code_to_response = {
    '200': _response_for_200,
    '403': _response_for_403,
    '404': _response_for_404,
    '429': _response_for_429,
}
_all_accept_content_types = (
    'application/json',
    'application/problem+json',
)


class BaseApi(api_client.Api):

    def _get_all_org_levels_mapped_args(
        self,
        level_description: typing.Optional[str] = None,
        code: typing.Optional[str] = None,
        budget_group: typing.Optional[str] = None,
        reporting_category: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if level_description is not None:
            _query_params["levelDescription"] = level_description
        if code is not None:
            _query_params["code"] = code
        if budget_group is not None:
            _query_params["budgetGroup"] = budget_group
        if reporting_category is not None:
            _query_params["reportingCategory"] = reporting_category
        if is_active is not None:
            _query_params["isActive"] = is_active
        args.query = _query_params
        return args

    async def _aget_all_org_levels_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get all org-levels
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_level_description,
            request_query_code,
            request_query_budget_group,
            request_query_reporting_category,
            request_query_is_active,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/configuration/v1/org-levels',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_all_org_levels_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get all org-levels
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_level_description,
            request_query_code,
            request_query_budget_group,
            request_query_reporting_category,
            request_query_is_active,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/configuration/v1/org-levels',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetAllOrgLevelsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_all_org_levels(
        self,
        level_description: typing.Optional[str] = None,
        code: typing.Optional[str] = None,
        budget_group: typing.Optional[str] = None,
        reporting_category: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_org_levels_mapped_args(
            level_description=level_description,
            code=code,
            budget_group=budget_group,
            reporting_category=reporting_category,
            is_active=is_active,
        )
        return await self._aget_all_org_levels_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_all_org_levels(
        self,
        level_description: typing.Optional[str] = None,
        code: typing.Optional[str] = None,
        budget_group: typing.Optional[str] = None,
        reporting_category: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_org_levels_mapped_args(
            level_description=level_description,
            code=code,
            budget_group=budget_group,
            reporting_category=reporting_category,
            is_active=is_active,
        )
        return self._get_all_org_levels_oapg(
            query_params=args.query,
        )

class GetAllOrgLevels(BaseApi):

    async def aget_all_org_levels(
        self,
        level_description: typing.Optional[str] = None,
        code: typing.Optional[str] = None,
        budget_group: typing.Optional[str] = None,
        reporting_category: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        validate: bool = False,
        **kwargs,
    ) -> ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponsePydantic:
        raw_response = await self.raw.aget_all_org_levels(
            level_description=level_description,
            code=code,
            budget_group=budget_group,
            reporting_category=reporting_category,
            is_active=is_active,
            **kwargs,
        )
        if validate:
            return RootModel[ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponsePydantic, raw_response.body)
    
    
    def get_all_org_levels(
        self,
        level_description: typing.Optional[str] = None,
        code: typing.Optional[str] = None,
        budget_group: typing.Optional[str] = None,
        reporting_category: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        validate: bool = False,
    ) -> ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponsePydantic:
        raw_response = self.raw.get_all_org_levels(
            level_description=level_description,
            code=code,
            budget_group=budget_group,
            reporting_category=reporting_category,
            is_active=is_active,
        )
        if validate:
            return RootModel[ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(ViewOrCreateOrganizationLevelsGetAllOrgLevelsResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        level_description: typing.Optional[str] = None,
        code: typing.Optional[str] = None,
        budget_group: typing.Optional[str] = None,
        reporting_category: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_org_levels_mapped_args(
            level_description=level_description,
            code=code,
            budget_group=budget_group,
            reporting_category=reporting_category,
            is_active=is_active,
        )
        return await self._aget_all_org_levels_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        level_description: typing.Optional[str] = None,
        code: typing.Optional[str] = None,
        budget_group: typing.Optional[str] = None,
        reporting_category: typing.Optional[str] = None,
        is_active: typing.Optional[bool] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_org_levels_mapped_args(
            level_description=level_description,
            code=code,
            budget_group=budget_group,
            reporting_category=reporting_category,
            is_active=is_active,
        )
        return self._get_all_org_levels_oapg(
            query_params=args.query,
        )

